# Generated by Django 3.1.5 on 2021-01-08 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoldName', models.CharField(max_length=50, verbose_name='Название склада')),
                ('EntatranceParkNumber', models.IntegerField(verbose_name='Номер платформы')),
                ('Responsible', models.CharField(max_length=50, verbose_name='Ответственный')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('Category', models.CharField(choices=[('Мебель', 'Мебель'), ('Стройматериалы', 'Строительные материалы'), ('Инструменты', 'Интсрументы для выполнения строительных,отделочных работ'), ('Техника', 'Технические средства, машины для строительных, отделочных работ')], max_length=50, verbose_name='Категория')),
                ('Amount', models.IntegerField(verbose_name='Количество')),
                ('ShelfLifeDay', models.IntegerField(verbose_name='Дней хранения')),
                ('ItemOption', models.TextField(verbose_name='Описание')),
                ('WareHouseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.warehouse', verbose_name='Склад')),
            ],
        ),
    ]
