# Generated by Django 3.1.5 on 2021-01-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210109_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='WareHouseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.warehouse'),
        ),
    ]
