# Generated by Django 3.1.5 on 2021-01-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210109_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ItemOption',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='items',
            name='ShelfLifeDay',
            field=models.IntegerField(blank=True, verbose_name='Дней хранения'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Responsible',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ответственный'),
        ),
    ]
