# Generated by Django 3.1.5 on 2021-01-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210109_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='ShelfLifeDay',
            field=models.IntegerField(verbose_name='Дней хранения'),
        ),
    ]
