# Generated by Django 3.1.5 on 2021-01-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210109_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='WareHouseID',
            new_name='foldid',
        ),
    ]
