# Generated by Django 3.1.5 on 2021-01-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210110_0214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WareHouse',
            new_name='Fold',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
