# Generated by Django 3.1.5 on 2021-01-11 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210110_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foldid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fold', verbose_name='Склад'),
        ),
    ]
