# Generated by Django 3.1.5 on 2021-01-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210111_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foldid',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='main.fold', verbose_name='Склад'),
        ),
    ]
