# Generated by Django 3.1.5 on 2021-01-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210111_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fold',
            old_name='FoldName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fold',
            old_name='EntatranceParkNumber',
            new_name='parknumber',
        ),
        migrations.RenameField(
            model_name='fold',
            old_name='Responsible',
            new_name='responsible',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='ItemOption',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='ShelfLifeDay',
            new_name='shelflifeday',
        ),
    ]
