# Generated by Django 3.1.5 on 2021-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210113_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldnewone',
            name='square',
            field=models.IntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='itemnewone',
            name='camedate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата поставки'),
        ),
    ]
